name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Greeting
        run: Write-Host "Hello, world!"

      - name: Simulate an error
        run:  Write-Host"About to fail" ; exit 1

      - name: Another greeting
        run: Write-Host "Hello, world!"
